/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRenewalsRouteImport } from './routes/_authenticated/renewals'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as IntakeTokenRouteImport } from './routes/intake.$token'
import { Route as QuestionnaireTokenRouteImport } from './routes/questionnaire.$token'
import { Route as OauthGoogleCalendarReturnRouteImport } from './routes/oauth/google-calendar/return'
import { Route as ApiPublicHooksBirthdayEmailsRouteImport } from './routes/api/public/hooks/birthday-emails'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRenewalsRoute = AuthenticatedRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const IntakeTokenRoute = IntakeTokenRouteImport.update({
  id: '/intake/$token',
  path: '/intake/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireTokenRoute = QuestionnaireTokenRouteImport.update({
  id: '/questionnaire/$token',
  path: '/questionnaire/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleCalendarReturnRoute =
  OauthGoogleCalendarReturnRouteImport.update({
    id: '/oauth/google-calendar/return',
    path: '/oauth/google-calendar/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBirthdayEmailsRoute =
  ApiPublicHooksBirthdayEmailsRouteImport.update({
    id: '/api/public/hooks/birthday-emails',
    path: '/api/public/hooks/birthday-emails',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/intake/$token': typeof IntakeTokenRoute
  '/questionnaire/$token': typeof QuestionnaireTokenRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/hooks/birthday-emails': typeof ApiPublicHooksBirthdayEmailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/intake/$token': typeof IntakeTokenRoute
  '/questionnaire/$token': typeof QuestionnaireTokenRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/hooks/birthday-emails': typeof ApiPublicHooksBirthdayEmailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/renewals': typeof AuthenticatedRenewalsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/intake/$token': typeof IntakeTokenRoute
  '/questionnaire/$token': typeof QuestionnaireTokenRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/hooks/birthday-emails': typeof ApiPublicHooksBirthdayEmailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/clients'
    | '/dashboard'
    | '/export'
    | '/pipeline'
    | '/profile'
    | '/renewals'
    | '/tasks'
    | '/intake/$token'
    | '/questionnaire/$token'
    | '/oauth/google-calendar/return'
    | '/api/public/hooks/birthday-emails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/clients'
    | '/dashboard'
    | '/export'
    | '/pipeline'
    | '/profile'
    | '/renewals'
    | '/tasks'
    | '/intake/$token'
    | '/questionnaire/$token'
    | '/oauth/google-calendar/return'
    | '/api/public/hooks/birthday-emails'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/export'
    | '/_authenticated/pipeline'
    | '/_authenticated/profile'
    | '/_authenticated/renewals'
    | '/_authenticated/tasks'
    | '/intake/$token'
    | '/questionnaire/$token'
    | '/oauth/google-calendar/return'
    | '/api/public/hooks/birthday-emails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  IntakeTokenRoute: typeof IntakeTokenRoute
  QuestionnaireTokenRoute: typeof QuestionnaireTokenRoute
  OauthGoogleCalendarReturnRoute: typeof OauthGoogleCalendarReturnRoute
  ApiPublicHooksBirthdayEmailsRoute: typeof ApiPublicHooksBirthdayEmailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/renewals': {
      id: '/_authenticated/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AuthenticatedRenewalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/intake/$token': {
      id: '/intake/$token'
      path: '/intake/$token'
      fullPath: '/intake/$token'
      preLoaderRoute: typeof IntakeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire/$token': {
      id: '/questionnaire/$token'
      path: '/questionnaire/$token'
      fullPath: '/questionnaire/$token'
      preLoaderRoute: typeof QuestionnaireTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-calendar/return': {
      id: '/oauth/google-calendar/return'
      path: '/oauth/google-calendar/return'
      fullPath: '/oauth/google-calendar/return'
      preLoaderRoute: typeof OauthGoogleCalendarReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/birthday-emails': {
      id: '/api/public/hooks/birthday-emails'
      path: '/api/public/hooks/birthday-emails'
      fullPath: '/api/public/hooks/birthday-emails'
      preLoaderRoute: typeof ApiPublicHooksBirthdayEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRenewalsRoute: typeof AuthenticatedRenewalsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRenewalsRoute: AuthenticatedRenewalsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  IntakeTokenRoute: IntakeTokenRoute,
  QuestionnaireTokenRoute: QuestionnaireTokenRoute,
  OauthGoogleCalendarReturnRoute: OauthGoogleCalendarReturnRoute,
  ApiPublicHooksBirthdayEmailsRoute: ApiPublicHooksBirthdayEmailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
